### ISSUE TITLE
v1 CityVoice Instance Builder: "Create your own CityVoice instance in 15 minutes for free"

### ISSUE THREAD

**Issue by daguar** [codeforamerica/cityvoice#209]
## Overview

I've got a working alpha to automate CityVoice deploys on Heroku — right now, just the default codebase and content gets deployed — here:
https://github.com/daguar/cityvoice-builder-heroku/ 
http://cityvoice-heroku-builder-dev.herokuapp.com/

Below I've spec'd out what I think a v1 of the "CityVoice Instance Builder" micro-app might look like below.

My core notion here is that for v1 builder, we **do not** attempt to make something that would be your production deploy — instead, we present **a simplified interface leaning heavily on defaults to let someone get a instance that has the key stuff customized quickly**. The hypothesis is that if users can get **something** up quickly, they'll be more likely to go do the (non-trivial) work of a full deploy (e.g., careful survey design, nicely-recorded audio files, etc.)

The goal is more to quickly convey (via the experience of building it) the different pieces they'll need for a CityVoice instance, and also experience what their deployment will be like.

Additionally, my thought is by starting with this less ambitious version, we can learn more quickly where the yaks in a CityVoice-Builder will be (e.g., is HTML5 audio recording terrible?)

In sum, I think this approach lets us sprint to a v1 that adds value today — "do it in 15 minutes" — rather than a partially-built builder that won't be usable until it's fully operational (Death Star, wah-nah-nah).

### Locations
- Add 1 via address (or map?) — use Google geocoder so they don't have to worry about it

### Questions
- Add 1 agree/disagree question
  - Text box for:
    - Question title (convert spaces to underscores for short name)
     - Question text
  - Record audio file in browser
- Add 1 voicemail question
  - Record audio in browser

### Record audio files
- Welcome message
- Thank you (last/goodbye) message
  
### Heroku
- Register an account (external to page — in a new tab)
- Deploy app
  
### Twilio (I have screenshots for this — it's straightforward)
- Register an account
- Get trial phone 
- Configure phone number for app

### Try it!
- Call in to trial phone #
- Go to web site

**Comment by jmadans** [comment]
BLUF: With the right client support, City decisionmakers are willing to launch with a "quickstart-ed" cityvoice campaign. 

While the jury is still out on on  our 5 midflight CityVoice pilots, the core assumption Dave made about the power of "deploying a thing in 15 minutes" has been tentatively validated. The value of letting government make a thing has -in large part - contented them to work within the default constraints of the builder. 

In fact, the functionality of the builder has somewhat outperformed Dave's original hypothesis that doing a quick, dirty prototype survey could be the bait to get a city to commit to a production deployment of City Voice. Instead, we have found that augmenting the builder experience with targeted client support (survey design, instance customization, project management) has yielded CityVoice campaigns that government officials are willing

**Comment by migurski** [comment]
For posterity, a link to the builder: https://cityvoice-setup.codeforamerica.org
