### ISSUE TITLE
Product Roadmap

### ISSUE THREAD

**Issue by daguar** [codeforamerica/cityvoice#212]
@rduecyg @lanebecker and I put together a basic product roadmap for how we're thinking about this. It can be found here:

https://docs.google.com/document/d/1Jk0DmOirgGPMiFH-Hr8fSUk-ierDaxC-Kv38J1erTLs/edit?usp=sharing

**Comment by jmadans** [comment]
FYI @daguar I'm working on a bare-bones roadmap that would take cityvoice all the way to go-to-market. Would be interested in sharing with you at CityVoice o'clock this Friday.

**Comment by daguar** [comment]
:+1:
