### ISSUE TITLE
Default signage (for sign generator micro-app)

### ISSUE THREAD

**Issue by daguar** [codeforamerica/cityvoice#213]
Per discussion with @rduecyg @mollymcleod, here's the plan:

- Needed elements for CityVoice sign
  - Phone number
  - Box/space for call-in code to be written by printers
  - CityVoice logo/icon
  - Survey-runner's logo (or text, maybe both)
  - Call to action (needs to be customizable)
    - Good to provide examples or templates
  - Title of the project ("what is this for?")
  - URL for this specific survey's web site
  - Contact info

- The "sign-builder" app
  - Simple web form with the above fields and a picture of an example sign
  - Starting with one (big) size
    - 24x36
    - Should put in documentation that bigger signs are better (in Outreach section)
 - Black and white
 - Will need to provide some interface that has (a) the name of each thing, and (b) the call-in code
   - Going to put in instructions for a URL on the live instance that has this simple list (needs dev work)

**Comment by jmadans** [comment]
Closing this issue for now as Dave et al was able to get to a v.1 of our sign generator. Related findings from the CityVoice pilots thus far has been that city staff use these as a first stab mock up to share with the in-house shop or vendor they task with sign creation.

**Comment by daguar** [comment]
ooo, that's super interesting! Great to know!
