### ISSUE TITLE
Printable list view of locations with call-in codes

### ISSUE THREAD

**Issue by daguar** [codeforamerica/cityvoice#217]
This is so that it's easy for people to write the call-in codes on signs, described here: https://github.com/codeforamerica/cityvoice-survey-builder/issues/47 This needs to be implemented here in the CityVoice app itself.

@jmadans — maybe a good thing to pair on to get you used to locally setting up and making PRs on these apps?

**Comment by jmadans** [comment]
@daguar 
Still have time / you can spare to pair / pls help me

**Comment by daguar** [comment]
This is a pretty small thing — I'd say 30 mins of pairing to get the plumbing done, and then I'd probably ask someone else to make it nice and printable.

I'd really like to pair with someone who might be "on call" for future CityVoice stuff just so this has the added benefit of some knowledge transmission. cc @migurski for your thoughts on this.

**Comment by migurski** [comment]
Yes let’s. I want to anyway to get the builder stuff integrated. Can we get 2 hours on the calendar this week?

**Comment by daguar** [comment]
Sure — if you happen to have time this afternoon we could also try to hop through it, they're both pretty straightforward and pairing should make it focused and quick.

**Comment by daguar** [comment]
Ah, @jmadans just mentioned you're out today so will look for a block next week :fist:.

**Comment by daguar** [comment]
This is in progress on https://github.com/daguar/cityvoice/tree/add-printable-view-of-locations

**Comment by jmadans** [comment]
I'm ready to close this issue, at least tentatively. Users haven't had trouble keeping track of their location id numbers as they move to print their signs. Actually, I'd argue it forces them to do some useful QA on their cityvoice site itself before launching.
