### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by josenberg** [codeforamerica/cityvoice#218]
There is a way to run this project in ruby 2.1 ? (or any plan to make it)

(Sorry for the poor english, i'm brazilian guy this is my first "issue")

**Comment by waltz** [comment]
It should run fine under Ruby 2.1. The current targeted Ruby version is 2.1.1. Are you having any problems running it with that Ruby version?

**Comment by daguar** [comment]
+1.

@josenberg: Bem-vindo! You can either:

1. Use Ruby 2.1.1 (with RVM, you can do `rvm install 2.1.1` and `rvm use 2.1.1`)
or
2. Edit the line in the Gemfile that says `ruby '2.1.1'` to use a different version and run `bundle install`. (It will probably work, but might not — 2.1.1 is the officially supported Ruby version for now.)

**Comment by josenberg** [comment]
thanks, I'll try it as soon as possible and share the results. 

:+1:
