### ISSUE TITLE
Upgrade to latest Ruby 2.1.x

### ISSUE THREAD

**Issue by daguar** [codeforamerica/cityvoice#219]

**Comment by boonrs** [comment]
:+1: I may do this for you as the current version of Ruby used is not supported by Heroku:
https://devcenter.heroku.com/articles/ruby-support#supported-runtimes

**Comment by daguar** [comment]
Yeah, we cheat on the builder app by going back to the Cedar stack. But a fix with conformation that everything still works fine would be welcomed!
