### ISSUE TITLE
Map only works after clicking a location

### ISSUE THREAD

**Issue by jmadans** [codeforamerica/cityvoice#221]
The map is grayed out until the user clicks on a location. 

<img width="1243" alt="screen shot 2015-07-08 at 5 34 40 pm" src="https://cloud.githubusercontent.com/assets/1261618/8585511/a8c52adc-2597-11e5-9621-9d5a036afa0a.png">

**Comment by daguar** [comment]
Was this resolved? I didn't see a fix so just wanted to check in on whether we were just considering this wont-fix.

**Comment by jmadans** [comment]
Oops, no. Was confused by Mike closing related issue in builder. THIS IS STILL A THING.

**Comment by migurski** [comment]
Very confused. This one works fine: http://fierce-brook-5461.herokuapp.com, but this one does not: https://ancient-thicket-9575.herokuapp.com. They appear to have identical code.

**Comment by daguar** [comment]
I did a quick fix to make sure the tiles load on a branch — the commit is here: https://github.com/codeforamerica/cityvoice/commit/bf0f5564b62f313cce5050da095a7a84bde9b649 

So the visual of the map will be loaded, but this quick fix does not address other interactions (map slipping, zoom) which still require a click on a marker.

**Comment by migurski** [comment]
Ooh, thanks. This will go a long way to alleviating the feeling of brokenness.

**Comment by daguar** [comment]
:+1: Yeah, this is probably a passable patch. I'm fairly sure the issue is something like just-in-time evaluation of stuff in the Backbone code.

**Comment by migurski** [comment]
Stupid DOM tricks.

**Comment by migurski** [comment]
It helps a little: https://ancient-thicket-9575.herokuapp.com

The map draws, but it’s wrong. Interestingly, I think it demonstrates what you were talking about with the bounds needing to be adjusted.

**Comment by daguar** [comment]
Oh wow how weird. Yeah, I think yanking Backbone out of this will make it easier to debug and will likely alone solve the issue.

**Comment by migurski** [comment]
I agree—I’ll take this approach when I work on the project with @jmadans on Monday.

**Comment by migurski** [comment]
I heard React was good, so I may try that.
