### ISSUE TITLE
Bring southbendvoices.com back to life!

### ISSUE THREAD

**Issue by jmadans** [codeforamerica/cityvoice#222]
Seems to be a DNS/server configuration issue with southbendvoices.com. Doesn't work when we drop the _www_ . Seems like it needs a proper A-record.

**Comment by migurski** [comment]
When I visit southbendvoices.com, I get redirected to www.southbendvoices.com. That seems like the best behavior—what am I missing?

**Comment by jmadans** [comment]
So it does. Let me investigate with Bracy to understand HOW it broke for her. Closing for now.

**Comment by daguar** [comment]
That was the behavior I _thought_ I set up way back when in 2013 @migurski , but I'm actually not getting that redirect right now.

**Comment by migurski** [comment]
How are you testing? I am seeing it my browser.

**Comment by daguar** [comment]
My own browser, Chrome private

**Comment by daguar** [comment]
Ah, Firefox private it lags but works. Not sure what's up with that.
