### ISSUE TITLE
More clearly convey results from agree/disagree questions

### ISSUE THREAD

**Issue by jmadans** [codeforamerica/cityvoice#227]
<img width="451" alt="screen shot 2015-08-28 at 12 39 00 pm" src="https://cloud.githubusercontent.com/assets/1261618/9555485/237cfa68-4d82-11e5-83c8-4734b1de77b9.png">
I am curious to hear from @daguar @rduecyg @ttmp about how guys arrived at this design. City partners have been confused by what the bars mean. 

I would argue this could be improved by simply adding the counts for how many survey respondents agreed or disagreed.

**Comment by daguar** [comment]
Yeah I actually agree with counts being better, and I don't recall any reasons for leaving it out other than moving fast by @rduecyg and @ttmp might.

**Comment by jmadans** [comment]
These work now!
