### ISSUE TITLE
Bar graphs not actually reflecting agree/disagree data

### ISSUE THREAD

**Issue by jmadans** [codeforamerica/cityvoice#232]
Why aren't the numerical answers being reflected on each of the location pages?
I have a hunch this has something to do with #230 (the numerical answers CSV isn't outputing data correctly) and is the main driver of #227 

<img width="328" alt="screen shot 2015-09-03 at 12 00 17 pm" src="https://cloud.githubusercontent.com/assets/1261618/9667961/b590e620-5233-11e5-8d70-31251181149d.png">

@daguar Any thoughts? I'm gonna try and tackle with @migurski in a Thursday afternoon edition of CityVoice O'clock

**Comment by daguar** [comment]
I've got a work-in-progress branch that changes how it's displayed to this:

<img width="415" alt="screen shot 2015-09-12 at 6 01 13 pm" src="https://cloud.githubusercontent.com/assets/994938/9834623/5d5ef48c-5978-11e5-85dd-ce2f9e9bb6c4.png">

So, the counts are shown, and the size of the bar reflects the %age.

This seems like the best approach I can imagine — sound okay @jmadans ?
